### ISSUE TITLE
Provide bash completion for carnotzet

### ISSUE THREAD

**Issue by matthyx** [swissquote/carnotzet#11]
Like Docker already provides bash completions for Docker and docker-compose, we should provide one for Carnotzet.

**Comment by mryan43** [comment]
Carnotzet doesn't have a binary (only java library and maven plugin). What do you mean ?

**Comment by matthyx** [comment]
Well, that does't prevent us from writing an auto-complete for mvn carnotzet:... ?
The idea would be to propose valid carnotzet commands, as well as completing service names, ...
(I think the detection could be based on what docker-compose is already providing)

**Comment by mryan43** [comment]
Ah yes it could be interesting !

**Comment by matthyx** [comment]
We could contribute to this one, which is blessed by Maven:
https://github.com/juven/maven-bash-completion
https://maven.apache.org/guides/mini/guide-bash-m2-completion.html

**Comment by matthyx** [comment]
Done.
https://github.com/juven/maven-bash-completion/pull/86
