### ISSUE TITLE
New feature : automatic reverse proxy for all applications

### ISSUE THREAD

**Issue by onigoetz** [swissquote/carnotzet#3]
Hi,

like we discussed it would be awesome to automatically create a reverse proxy that links all webapps behind a single host and port, thus avoiding cross-domain issues and long configuration of a separate reverse proxy.

**Comment by mryan43** [comment]
For the "url path to container" mapping, we can the module name by convention and allow an override in carnotzet. properies.

we should also detect conflicts, for example I dont think the example voting app can work with this extension because both voting and result app serve on '/'

**Comment by mryan43** [comment]
Added an implementation of that feature as an extension in a separate repository : https://github.com/swissquote/carnotzet-extension-reverse-proxy

Let's continue the discussion on the issues of that repo.
